/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistema.view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sistema.dao.UtilizadorDAO;
import sistema.model.Funcionario;
import sistema.model.Medico;
import sistema.model.Utilizador;
import sistema.model.Especialidade;
import sistema.dao.EspecialidadeDAO;
import sistema.dao.FuncionarioDAO;
import sistema.dao.MedicoDAO;


/**
 *
 * @author Wilson Lopes
 */
public class FormularioFuncionario extends javax.swing.JFrame {
    
    public void listar(){
        FuncionarioDAO dao = new FuncionarioDAO();
        List<Funcionario> lista = dao.listarFuncionarios();
        DefaultTableModel dados = (DefaultTableModel) tabela.getModel();
        dados.setRowCount(0);
        
        for (Funcionario f : lista) {
            dados.addRow(new Object[]{
                 
                f.getNome(),
                f.getBi(),
                f.getCodigo(),
                f.getCargo(),
                 f.getHorario(),
                f.getUtilizador()
            });
        }
    }

    public FormularioFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        painelGuias = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtBi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbxEspecialidade = new javax.swing.JComboBox();
        txtHorario = new javax.swing.JTextField();
        cbxCargo1 = new javax.swing.JComboBox<>();
        txtNmedico = new javax.swing.JTextField();
        txtUsu = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtF = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(27, 10, 7));

        jLabel1.setBackground(new java.awt.Color(27, 10, 7));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FUNCIONÁRIOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(385, 385, 385)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        painelGuias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nº do Documento de Identificação");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        txtBi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBiActionPerformed(evt);
            }
        });
        jPanel2.add(txtBi, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 230, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nome");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 196, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Especialidade");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Número do Medico");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Horário");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Utilizador");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 60, -1));

        cbxEspecialidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxEspecialidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NENHUMA" }));
        cbxEspecialidade.setAutoscrolls(true);
        cbxEspecialidade.setEnabled(false);
        cbxEspecialidade.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbxEspecialidadeAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cbxEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEspecialidadeActionPerformed(evt);
            }
        });
        jPanel2.add(cbxEspecialidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 170, 30));

        txtHorario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHorarioActionPerformed(evt);
            }
        });
        jPanel2.add(txtHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 230, 30));

        cbxCargo1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxCargo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atendente", "Médico" }));
        cbxCargo1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCargo1ItemStateChanged(evt);
            }
        });
        cbxCargo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxCargo1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbxCargo1MouseEntered(evt);
            }
        });
        cbxCargo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCargo1ActionPerformed(evt);
            }
        });
        // Ação para alterar o estado da ComboBox2
        cbxCargo1.addItemListener(new java.awt.event.ItemListener() {
            @Override
            public void itemStateChanged(java.awt.event.ItemEvent e) {
                if (e.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
                    if (cbxCargo1.getSelectedItem().equals("Médico")) {
                        cbxEspecialidade.setEnabled(true);
                        txtNmedico.setEnabled(true);
                    } else {
                        cbxEspecialidade.setEnabled(false);
                        txtNmedico.setEnabled(false);
                        txtNmedico.setText("");
                        // Seleciona "Nenhuma" e desabilita
                    }
                }
            }
        });
        jPanel2.add(cbxCargo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 140, 30));

        txtNmedico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNmedico.setEnabled(false);
        jPanel2.add(txtNmedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 142, 200, 30));
        jPanel2.add(txtUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 130, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Cargo");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));
        jPanel2.add(txtF, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, -1, -1));

        painelGuias.addTab("Registro de Funcionário", jPanel2);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Nome");

        jTextField7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/imagens/icones/search_icon (2).png"))); // NOI18N
        jButton6.setText("Pesquisar");
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Documento", "Código", "Cargo", "Horario", "Utilizador", "N Medico", "Especialidade", "Passe"
            }
        ));
        tabela.setAutoscrolls(false);
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(50, 50, 50))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        painelGuias.addTab("Lista de Funcionários", jPanel3);

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/imagens/icones/add_plus_icon.png"))); // NOI18N
        btnNovo.setText("NOVO");
        btnNovo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNovo.setIconTextGap(2);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/imagens/icones/save_icon (2).png"))); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSalvar.setIconTextGap(2);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/imagens/icones/refresh_icon.png"))); // NOI18N
        btnAtualizar.setText("ATUALIZAR");
        btnAtualizar.setIconTextGap(2);
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/imagens/icones/dustbin_bin_trush_icon.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(painelGuias, javax.swing.GroupLayout.PREFERRED_SIZE, 918, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btnNovo)
                        .addGap(110, 110, 110)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(btnEliminar)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelGuias, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBiActionPerformed

    private void txtHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHorarioActionPerformed

    private void cbxEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEspecialidadeActionPerformed
       
    }//GEN-LAST:event_cbxEspecialidadeActionPerformed

    private void cbxCargo1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCargo1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCargo1ItemStateChanged

    private void cbxCargo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxCargo1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCargo1MouseClicked

    private void cbxCargo1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxCargo1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCargo1MouseEntered

    private void cbxCargo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCargo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCargo1ActionPerformed
    
    

    
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Medico m = new Medico();
        Funcionario f = new Funcionario();
        MedicoDAO mDAO = new MedicoDAO();
        FuncionarioDAO fDAO = new FuncionarioDAO();
        
        f.setNome(txtNome.getText());
        f.setBi(txtBi.getText());
        f.setHorario(txtHorario.getText());
        f.setCargo(cbxCargo1.getSelectedItem().toString());
        f.setUtilizador(txtUsu.getText());
        fDAO.salvarFuncionario(f);
        JOptionPane.showMessageDialog(null, "Funcionario Cadastrado com sucesso");
        if (cbxCargo1.getSelectedItem() == "Medico") {
            m.setNumero(Integer.parseInt(txtNmedico.getText()));
            m.setEspecialidade(m.getEspecialidade());
            m.setFuncionario(f);
            mDAO.salvarMedico(m);
            JOptionPane.showMessageDialog(null, "Medico Cadastrado com sucesso");
        }
        
        
    }//GEN-LAST:event_btnSalvarActionPerformed
    
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listar();
    }//GEN-LAST:event_formWindowActivated

    private void cbxEspecialidadeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbxEspecialidadeAncestorAdded
     EspecialidadeDAO dao = new EspecialidadeDAO();
     List<Especialidade> lista = dao.listarEspecialidade();
     cbxEspecialidade.removeAllItems();
     for(Especialidade e : lista){
         cbxEspecialidade.addItem(e);
     }
    }//GEN-LAST:event_cbxEspecialidadeAncestorAdded

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        Medico m = new Medico();
        Funcionario f = new Funcionario();
        MedicoDAO mDAO = new MedicoDAO();
        FuncionarioDAO fDAO = new FuncionarioDAO();

        f.setNome(txtNome.getText());
        f.setBi(txtBi.getText());
        f.setHorario(txtHorario.getText());
        f.setCargo(cbxCargo1.getSelectedItem().toString());
        f.setUtilizador(txtUsu.getText());
        fDAO.salvarFuncionario(f);
        JOptionPane.showMessageDialog(null, "Funcionario Atualizado com sucesso");
        if (cbxCargo1.getSelectedItem() == "Medico") {
            m.setNumero(Integer.parseInt(txtNmedico.getText()));
            m.setEspecialidade(m.getEspecialidade());
            m.setFuncionario(f);
            mDAO.atualizarMedico(m);
            JOptionPane.showMessageDialog(null, "Medico Cadastrado com sucesso");
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
       
    }//GEN-LAST:event_tabelaMouseClicked

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbxCargo1;
    private javax.swing.JComboBox cbxEspecialidade;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTabbedPane painelGuias;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtBi;
    private javax.swing.JLabel txtF;
    private javax.swing.JTextField txtHorario;
    private javax.swing.JTextField txtNmedico;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtUsu;
    // End of variables declaration//GEN-END:variables
}
