/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistema.view;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sistema.dao.PacienteDAO;
import sistema.model.Paciente;
import sistema.utilitarios.Utilitarios;

/**
 *
 * @author Wilson Lopes
 */
public class FormularioPaciente extends javax.swing.JFrame {

    public void listar() {
        PacienteDAO daoP = new PacienteDAO();
        List<Paciente> lista = daoP.listarPaciente();
        DefaultTableModel dadosPaciente = (DefaultTableModel) tabela.getModel();
        dadosPaciente.setRowCount(0);

        for (Paciente p : lista) {
            dadosPaciente.addRow(new Object[]{
                p.getNome(),
                p.getNumeroDoc(),
                //idade, // Adiciona a idade calculada na tabela
                p.getDataNascimento(),
                p.getTelefone(),
                p.getProvincia(),
                p.getMunicipio(),
                p.getBairro()
            });
        }

    }

    public FormularioPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        painelGuias = new javax.swing.JTabbedPane();
        jPainelDados = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtBi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbxProvincia = new javax.swing.JComboBox<>();
        cbxMunicipio = new javax.swing.JComboBox<>();
        dataChooser = new com.toedter.calendar.JDateChooser();
        txtTeste = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtFiltro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnPesquisar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(27, 10, 7));

        jLabel1.setBackground(new java.awt.Color(27, 10, 7));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PACIENTES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, -1));

        painelGuias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPainelDados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nº do Documento de Identificação");
        jPainelDados.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        txtBi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBiActionPerformed(evt);
            }
        });
        jPainelDados.add(txtBi, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 230, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nome");
        jPainelDados.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPainelDados.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 196, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Telefone");
        jPainelDados.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, -1, -1));

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)###-###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPainelDados.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 167, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Província");
        jPainelDados.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Município");
        jPainelDados.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Bairro");
        jPainelDados.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, -1));

        txtBairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroActionPerformed(evt);
            }
        });
        jPainelDados.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 140, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Data de Nascimento");
        jPainelDados.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        cbxProvincia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONAR", "Bengo", "Benguela", "Bié", "Cabinda", "Cuando Cubango", "Cuanza Norte", "Cuanza Sul", "Cunene", "Huambo", "Huíla", "Luanda", "Lunda Norte", "Lunda Sul", "Malanje", "Moxico", "Uíge", "Zaire" }));
        cbxProvincia.setToolTipText("");
        cbxProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProvinciaActionPerformed(evt);
            }
        });
        cbxProvincia.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                String provinciaSelecionado = (String) cbxProvincia.getSelectedItem();
                atualizarCbxMunicipio(provinciaSelecionado);
            }
        });
        jPainelDados.add(cbxProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 200, 30));

        cbxMunicipio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxMunicipio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE A PROVINCIA" }));
        jPainelDados.add(cbxMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 230, 30));

        dataChooser.setDateFormatString("yyyy-MM-dd");
        dataChooser.setMaxSelectableDate(new java.util.Date(253370768464000L));
        dataChooser.setMinSelectableDate(new java.util.Date(-62135765936000L));
        jPainelDados.add(dataChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 42, 140, 30));

        txtTeste.setText("jLabel8");
        jPainelDados.add(txtTeste, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 110, -1));

        painelGuias.addTab("Registro de Paciente", jPainelDados);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Filtrar por");

        txtFiltro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Documento", "Nascimento", "Telefone", "Provincia", "Municipio", "Bairro"
            }
        ));
        tabela.setAutoscrolls(false);
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/imagens/icones/search_icon (2).png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisar)
                        .addGap(381, 381, 381))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        painelGuias.addTab("Lista de Pacientes", jPanel3);

        getContentPane().add(painelGuias, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 50, 900, 310));

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/imagens/icones/save_icon (2).png"))); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSalvar.setIconTextGap(2);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 120, 35));

        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/imagens/icones/refresh_icon.png"))); // NOI18N
        btnAtualizar.setText("ATUALIZAR");
        btnAtualizar.setIconTextGap(2);
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 120, 35));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/imagens/icones/dustbin_bin_trush_icon.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, -1, 35));

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/imagens/icones/add_plus_icon.png"))); // NOI18N
        btnNovo.setText("NOVO");
        btnNovo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNovo.setIconTextGap(2);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarCbxMunicipio(String provinciaSelecionada) {
        String[] municipios;
        switch (provinciaSelecionada) {
            case "Bengo":
                municipios = new String[]{"SELECIONE O MUNICIPIO", "Ambriz", "Bula Atumba", "Dande", "Dembos", "Nambuangongo", "Pango Aluquém"};
                break;
            case "Benguela":
                municipios = new String[]{"SELECIONE O MUNICIPIO", "Baía Farta", "Balombo", "Benguela", "Bocoio", "Caimbambo", "Catumbela", "Chongoroi", "Cubal", "Ganda", "Lobito"};
                break;
            case "Bié":
                municipios = new String[]{"SELECIONE O MUNICIPIO", "Andulo", "Camacupa", "Catabola", "Chinguar", "Chitembo", "Cuemba", "Cunhinga", "Cuito", "Nharea"};
                break;
            case "Cabinda":
                municipios = new String[]{"SELECIONE O MUNICIPIO", "Cabinda", "Cacongo", "Buco-Zau", "Belize"};
                break;
            case "Cuando Cubango":
                municipios = new String[]{"SELECIONE O MUNICIPIO", "Calai", "Cuangar", "Cuchi", "Cuito Cuanavale", "Dirico", "Mavinga", "Menongue", "Nancova", "Rivungo"};
                break;
            case "Cuanza Norte":
                municipios = new String[]{"SELECIONE O MUNICIPIO", "Ambaca", "Banga", "Bolongongo", "Cambambe", "Cazengo", "Golungo Alto", "Gonguembo", "Lucala", "Quiculungo", "Samba Cajú"};
                break;
            case "Cuanza Sul":
                municipios = new String[]{"SELECIONE O MUNICIPIO", "Gabela", "Cassongue", "Cela", "Conda", "Ebo", "Libolo", "Mussende", "Porto Amboim", "Quilenda", "Quibala", "Seles", "Sumbe"};
                break;
            case "Cunene":
                municipios = new String[]{"SELECIONE O MUNICIPIO", "Cahama", "Cuanhama", "Curoca", "Cuvelai", "Namacumbe", "Ombadja"};
                break;
            case "Huambo":
                municipios = new String[]{"SELECIONE O MUNICIPIO", "Longonjo", "Bailundo", "Chicala Choloanga", "Mungo", "Londuimbale", "Tchindjendje", "Ucuma", "Cachiungo", "Caála", "Ecunha", "Huambo"};
                break;
            case "Huíla":
                municipios = new String[]{"SELECIONE O MUNICIPIO", "Caconda", "Cacula", "Caluquembe", "Gambos", "Chibia", "Chicomba", "Chipindo", "Cuvango", "Humpata", "Jamba", "Lubango", "Matala", "Quilengue", "Quipungo"};
                break;
            case "Luanda":
                municipios = new String[]{"SELECIONE O MUNICIPIO", "Icolo e Bengo", "Quiçama", "Luanda", "Cacuaco", "Cazenga", "Viana", "Belas", "Kilamba Kiaxi", "Talatona"};
                break;
            case "Lunda Norte":
                municipios = new String[]{"SELECIONE O MUNICIPIO", "Cambulo", "Capenda Camulemba", "Caungula", "Chitato", "Cuango", "Cuilo", "Lubalo", "Lucapa", "Lóvua", "Xá-Muteba"};
                break;
            case "Lunda Sul":
                municipios = new String[]{"SELECIONE O MUNICIPIO", "Cacolo", "Dala", "Muconda", "Saurimo"};
                break;
            case "Malanje":
                municipios = new String[]{"SELECIONE O MUNICIPIO", "Cacuso", "Caombo", "Cambundi-Catembo", "Cangandala", "Cuaba Nzogo", "Cunda-Dia-Baze", "Luquembo", "Malanje", "Marimba", "Massango", "Mucari", "Quela", "Quirima"};
                break;
            case "Moxico":
                municipios = new String[]{"SELECIONE O MUNICIPIO", "Alto Zambeze", "Bundas", "Camanongue", "Léua", "Luau", "Luacano", "Moxico", "Luchazes", "Cameia"};
                break;
            case "Namibe":
                municipios = new String[]{"SELECIONE O MUNICIPIO", "Moçamedes", "Camucuio", "Bibala", "Virei", "Tômbua"};
                break;
            case "Uíge":
                municipios = new String[]{"SELECIONE O MUNICIPIO", "Uíge", "Alto Cauale", "Ambuila", "Bembe", "Buengas", "Bungo", "Milunga", "Damba", "Maquela do Zombo", "Mucaba", "Negage", "Puri", "Quimbele", "Quitexe", "Sanza Pombo", "Songo"};
                break;
            case "Zaire":
                municipios = new String[]{"SELECIONE O MUNICIPIO", "Mbanza Congo", "Soyo", "Nzeto", "Cuimba", "Nóqui", "Tomboco"};
                break;
            default:
                municipios = new String[]{"SELECIONE A PROVÍNCIA"};
        }

        cbxMunicipio.setModel(new DefaultComboBoxModel<>(municipios));
    }

    private void txtBiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBiActionPerformed

    private void cbxProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProvinciaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbxProvinciaActionPerformed

    private void txtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        String nome = "%" + txtFiltro.getText() + "%";
        PacienteDAO dao = new PacienteDAO();
        List<Paciente> lista = dao.filtrarPacientes(nome);
        DefaultTableModel dados = (DefaultTableModel) tabela.getModel();
        dados.setRowCount(0);

        for (Paciente p : lista) {
            dados.addRow(new Object[]{
                p.getNome(),
                p.getNumeroDoc(),
                p.getDataNascimento(),
                p.getTelefone(),
                p.getProvincia(),
                p.getMunicipio(),
                p.getBairro()
            });
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        Paciente p = new Paciente();
        p.setProvincia(cbxProvincia.getSelectedItem().toString());
        p.setMunicipio(cbxMunicipio.getSelectedItem().toString());
        p.setBairro(txtBairro.getText());
        p.setNumeroDoc(txtBi.getText());
        p.setNome(txtNome.getText());
        p.setTelefone(txtTelefone.getText());
        // FORMATAR A DATA
        Date dataSelecionada = dataChooser.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String dataFormatada = dateFormat.format(dataSelecionada);
        p.setDataNascimento(dataFormatada);

        PacienteDAO pDao = new PacienteDAO();
        pDao.salvarPaciente(p);

        Utilitarios util = new Utilitarios();
        util.limpaTela(jPainelDados);
        cbxProvincia.setSelectedIndex(0);
        cbxMunicipio.setSelectedIndex(0);
        dataChooser.setDate(null);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listar();
    }//GEN-LAST:event_formWindowActivated

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed

        Paciente p = new Paciente();
        p.setProvincia(cbxProvincia.getSelectedItem().toString());
        p.setMunicipio(cbxMunicipio.getSelectedItem().toString());
        p.setBairro(txtBairro.getText());
        p.setNumeroDoc(txtBi.getText());
        p.setNome(txtNome.getText());
        p.setTelefone(txtTelefone.getText());
        // FORMATAR A DATA
        Date dataSelecionada = dataChooser.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String dataFormatada = dateFormat.format(dataSelecionada);
        p.setDataNascimento(dataFormatada);

        PacienteDAO pDao = new PacienteDAO();
        pDao.atualizarPaciente(p);

        Utilitarios util = new Utilitarios();
        util.limpaTela(jPainelDados);
        cbxProvincia.setSelectedIndex(0);
        cbxMunicipio.setSelectedIndex(0);
        dataChooser.setDate(null);

    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        Paciente obj = new Paciente();
        obj.setNumeroDoc(txtBi.getText());
        PacienteDAO dao = new PacienteDAO();
        dao.eliminarPaciente(obj);
        Utilitarios util = new Utilitarios();
        util.limpaTela(jPainelDados);

        cbxProvincia.setSelectedIndex(0);
        cbxMunicipio.setSelectedIndex(0);
        dataChooser.setDate(null);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        painelGuias.setSelectedIndex(0);
        txtNome.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
        txtBi.setText(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());
        String dataString = tabela.getValueAt(tabela.getSelectedRow(), 2).toString();
        txtBairro.setText(tabela.getValueAt(tabela.getSelectedRow(), 6).toString());
        txtTeste.setText(dataString);
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); // Ajustando o formato da data
        Date data = null;
        try {
            data = dateFormat.parse(dataString);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        dataChooser.setDate(data);
        txtTelefone.setText(tabela.getValueAt(tabela.getSelectedRow(), 3).toString());
        cbxProvincia.setSelectedItem(tabela.getValueAt(tabela.getSelectedRow(), 4).toString());
        cbxMunicipio.setSelectedItem(tabela.getValueAt(tabela.getSelectedRow(), 5).toString());
        
    }//GEN-LAST:event_tabelaMouseClicked

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        painelGuias.setSelectedIndex(0);
        Utilitarios util = new Utilitarios();
        util.limpaTela(jPainelDados);
        cbxProvincia.setSelectedIndex(0);
        cbxMunicipio.setSelectedIndex(0);
        dataChooser.setDate(null);
    }//GEN-LAST:event_btnNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbxMunicipio;
    private javax.swing.JComboBox<String> cbxProvincia;
    private com.toedter.calendar.JDateChooser dataChooser;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPainelDados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane painelGuias;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtBi;
    private javax.swing.JTextField txtFiltro;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtTelefone;
    private javax.swing.JLabel txtTeste;
    // End of variables declaration//GEN-END:variables
}
